spring:
  application:
    name: listable-repo

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    properties.hibernate.hbm2ddl.auto: create

  data:
    rest:
      base-path: /api

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/listable?useSSL=false
    username: root
    password: Flowers101

management:
  security:
    enabled: false

server:
  port: 8090

debug: false

INSTANCE_CONNECTION_NAME: listable-189821:us-east1:listable-repo-1
database: listable
user: root